# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
