# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='published_date',
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
