# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160505_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
