# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160505_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
