# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160505_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
